### ISSUE TITLE
docker-compose up issue: incorrect password

### ISSUE THREAD

**Issue by geofflangenderfer** [aave/aave-v3-core#679]
Hey y'all, I'm trying to run the tests. I'm getting stuck getting docker setup:
```
$ sudo docker-compose up
aave-v3-core-contracts-env-1  | npm ERR! code E401
aave-v3-core-contracts-env-1  | npm ERR! Incorrect or missing password.
aave-v3-core-contracts-env-1  | npm ERR! If you were trying to login, change your password, create an
aave-v3-core-contracts-env-1  | npm ERR! authentication token or enable two-factor authentication then
aave-v3-core-contracts-env-1  | npm ERR! that means you likely typed your password in incorrectly.
aave-v3-core-contracts-env-1  | npm ERR! Please try again, or recover your password at:
aave-v3-core-contracts-env-1  | npm ERR!     https://www.npmjs.com/forgot
aave-v3-core-contracts-env-1  | npm ERR!
aave-v3-core-contracts-env-1  | npm ERR! If you were doing some other operation then your saved credentials are
aave-v3-core-contracts-env-1  | npm ERR! probably out of date. To correct this please try logging in again with:
aave-v3-core-contracts-env-1  | npm ERR!     npm login
aave-v3-core-contracts-env-1  |
aave-v3-core-contracts-env-1  | npm ERR! A complete log of this run can be found in:
aave-v3-core-contracts-env-1  | npm ERR!     /home/node/.npm/_logs/2022-05-15T21_29_09_755Z-debug-0.log
aave-v3-core-contracts-env-1 exited with code 1

$
```

**Comment by geofflangenderfer** [comment]
got log contents
```
4646 verbose stack HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="GitHub Package Registry"
4646 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:78:17
4646 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
4646 verbose stack     at async Arborist.[nodeFromEdge] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1108:19)
4646 verbose stack     at async Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:976:11)
4646 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
4646 verbose stack     at async Promise.all (index 1)
4646 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
4646 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:156:5)
4646 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:78:5)
4647 verbose statusCode 401
4648 verbose pkgid @aave/deploy-v3@^1.21.1-beta.4
4649 verbose cwd /home/g/work/aave-v3-core
4650 verbose Linux 5.9.16-1-MANJARO
4651 verbose node v16.15.0
4652 verbose npm  v8.10.0
4653 error code E401
4654 error Incorrect or missing password.
4655 error If you were trying to login, change your password, create an
4655 error authentication token or enable two-factor authentication then
4655 error that means you likely typed your password in incorrectly.
4655 error Please try again, or recover your password at:
4655 error     https://www.npmjs.com/forgot
4655 error
4655 error If you were doing some other operation then your saved credentials are
4655 error probably out of date. To correct this please try logging in again with:
4655 error     npm login
4656 verbose exit 1
4657 timing npm Completed in 32732ms
4658 verbose unfinished npm timer reify 1652650527946
4659 verbose unfinished npm timer reify:loadTrees 1652650527964
4660 verbose code 1
4661 error A complete log of this run can be found in:
4661 error     /home/g/.npm/_logs/2022-05-15T21_35_27_760Z-debug-0.log

```

**Comment by geofflangenderfer** [comment]
I [tried this](https://stackoverflow.com/questions/58919401/installing-packages-from-github-npm-registry-auth-error-401) and got:
```
$ npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/@aave%2fdeploy-v3 - npm package "deploy-v3" does not exist under owner "aave"
npm ERR! 404
npm ERR! 404  '@aave/deploy-v3@^1.21.1-beta.4' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/g/.npm/_logs/2022-05-15T21_41_53_017Z-debug-0.log
```

**Comment by miguelmtzinf** [comment]
The deploy package is available [here](https://www.npmjs.com/package/@aave/deploy-v3).
Happy to reopen this issue if you need any help.
